### ISSUE TITLE
http://localhost:3000/api/products can't be reached 

### ISSUE THREAD

**Issue by HolyCal** [HolyCal/P5#3]
I have set up the local host and it is listening on port 3000 yet the http://localhost:3000/api/products still does not load

**Comment by AccessiT3ch** [comment]
@HolyCal I'm not entirely sure what's not working on your end, I had to re-run `npm install`, but then I was able to run `npm run` and am now able to load that url.

Maybe a screenshot might help to debug?

**Comment by HolyCal** [comment]
![image](https://user-images.githubusercontent.com/57889079/202117910-be745adf-61f0-432d-95f8-448f95ed9661.png)

This is what i've typed in the terminal, but i'm still getting:

![image](https://user-images.githubusercontent.com/57889079/202118084-4fd30cfd-5a0e-473c-95ec-913b9cb9b970.png)

**Comment by HolyCal** [comment]
@AccessiT3ch

**Comment by HolyCal** [comment]
![image](https://user-images.githubusercontent.com/57889079/202120887-be4fe820-3d1e-4f74-94a8-25c7739794c2.png)

After following the demonstration this page loads this array. But for me it does not. I'm not sure if you can access this link but i will share it in case you can. 

https://app.livestorm.co/openclassrooms-1/project-5-coding-demonstration/live?s=1a52c812-22c6-4c6a-a02a-5d091a89ddac#/chat

**Comment by HolyCal** [comment]
I'm also trying to use the JSON Viewer extension to view the page

**Comment by AccessiT3ch** [comment]
@HolyCal - Ah ok, it looks like you're using Github's Codespaces right? If you are opening the codespace in the browser it's going to be a little different than opening it locally. I would recommend opening your codespace in your local VS Code to get the normal localhost behavior.

<img width="462" alt="Screenshot 2022-11-16 at 9 33 19 AM" src="https://user-images.githubusercontent.com/95449364/202252252-becb291a-0172-4d59-9d3f-1728a99356ba.png">

Otherwise, if you continue working in the browser, you can access your exposed ports by clicking on the ports tab to see where the port is being forwarded.

<img width="973" alt="Screenshot 2022-11-16 at 9 32 27 AM" src="https://user-images.githubusercontent.com/95449364/202252688-923bdc9c-fd29-43ab-bb4b-d01f76e2c569.png">
<img width="966" alt="Screenshot 2022-11-16 at 9 32 34 AM" src="https://user-images.githubusercontent.com/95449364/202252771-9dc93ef6-8853-48d6-9b1e-bcd04944dc3b.png">
